"""
git_reader.py — git data layer

The only module that talks to git. Everything else receives plain dicts and lists.
Uses subprocess + custom delimiters to parse git output reliably without regex fragility.
All subprocess calls use encoding="utf-8", errors="ignore" — Windows cp1252 default
causes UnicodeDecodeError on diffs containing non-ASCII bytes (e.g. em-dashes).
"""

import subprocess
from pathlib import Path


MAX_FILE_BYTES = 50_000

TEXT_EXTENSIONS = {
    ".py", ".js", ".ts", ".jsx", ".tsx",
    ".java", ".go", ".rs", ".c", ".cpp", ".h",
    ".html", ".css", ".scss",
    ".json", ".yaml", ".yml", ".toml", ".ini", ".env.example",
    ".md", ".txt", ".sh", ".sql",
}

COMMIT_DELIMITER = "||DOCIT||"
FIELD_DELIMITER  = "||FIELD||"

MAX_DIFF_CHARS = 8_000  # ~2000 tokens


def get_repo_root(path: Path | None = None) -> Path:
    """
    Returns the absolute path to the root of the git repo.
    Searches from `path` if given, otherwise from cwd.
    Raises RuntimeError if not inside a git repo.
    """
    result = subprocess.run(
        ["git", "rev-parse", "--show-toplevel"],
        capture_output=True,
        encoding="utf-8",
        errors="ignore",
        cwd=path,
    )
    if result.returncode != 0:
        raise RuntimeError(
            "Not inside a git repository. "
            "Run `doc-it run` from within a git repo, or pass --repo <path>."
        )
    return Path(result.stdout.strip())


def get_all_files(repo_root: Path) -> list[dict]:
    """
    Returns tracked text files in the repo.
    Each entry: {"path": str, "content": str}

    Skips binaries, files over MAX_FILE_BYTES, and unsupported extensions.
    """
    result = subprocess.run(
        ["git", "ls-files"],
        capture_output=True,
        encoding="utf-8",
        errors="ignore",
        cwd=repo_root,
    )
    if result.returncode != 0:
        raise RuntimeError(f"git ls-files failed: {result.stderr.strip()}")

    files = []
    for rel_path in result.stdout.splitlines():
        path = repo_root / rel_path

        if path.suffix.lower() not in TEXT_EXTENSIONS:
            continue
        if not path.exists():
            continue
        if path.stat().st_size > MAX_FILE_BYTES:
            continue

        try:
            content = path.read_text(encoding="utf-8", errors="ignore")
            files.append({"path": rel_path, "content": content})
        except Exception:
            continue

    return files


def get_commits_since(repo_root: Path, sha: str | None) -> list[dict]:
    """
    Returns commits since `sha` (exclusive), newest first.
    If sha is None, returns all commits in the repo.

    Each entry: {sha, short_sha, message, author, date}
    """
    log_format = FIELD_DELIMITER.join(["%H", "%s", "%an", "%aI"])
    fmt_arg = f"--format={COMMIT_DELIMITER}{log_format}"

    cmd = ["git", "log", fmt_arg, f"{sha}..HEAD"] if sha else ["git", "log", fmt_arg]

    result = subprocess.run(
        cmd,
        capture_output=True,
        encoding="utf-8",
        errors="ignore",
        cwd=repo_root,
    )
    if result.returncode != 0:
        raise RuntimeError(f"git log failed: {result.stderr.strip()}")

    commits = []
    for entry in result.stdout.split(COMMIT_DELIMITER):
        entry = entry.strip()
        if not entry:
            continue
        fields = entry.split(FIELD_DELIMITER)
        if len(fields) != 4:
            continue
        full_sha, message, author, date = fields
        commits.append({
            "sha":       full_sha.strip(),
            "short_sha": full_sha.strip()[:7],
            "message":   message.strip(),
            "author":    author.strip(),
            "date":      date.strip(),
        })

    return commits


def get_diff_for_commit(repo_root: Path, sha: str) -> str:
    """
    Returns the diff for a single commit as a string.
    Truncated to MAX_DIFF_CHARS if the diff is large.
    """
    result = subprocess.run(
        # Exclude DEVLOG.md from the diff — it's auto-generated by doc-it itself
        # and would cause the LLM to summarize its own previous output (recursive noise).
        ["git", "show", "--stat", "--patch", sha, "--", ".", ":(exclude)DEVLOG.md"],
        capture_output=True,
        encoding="utf-8",
        errors="ignore",
        cwd=repo_root,
    )
    if result.returncode != 0:
        raise RuntimeError(f"git show failed for {sha}: {result.stderr.strip()}")

    diff = result.stdout
    if len(diff) > MAX_DIFF_CHARS:
        diff = diff[:MAX_DIFF_CHARS] + f"\n\n[diff truncated at {MAX_DIFF_CHARS} chars]"

    return diff
